### ISSUE TITLE
Update to Webpack 2

### ISSUE THREAD

**Issue by BWortman** [fusionalliance/autorenter-angular1#46]
There are known problems with font loaders in Webpack 2.

Please recommend if you'd like to use a different build/bundle tool... I'm not married to Webpack.

**Comment by rclanan** [comment]
[WIP] Branch [update-wepack](https://github.com/fusionalliance/autorenter-angular1/tree/update-webpack)

**Comment by BWortman** [comment]
somewhat duplicates #20
