### ISSUE TITLE
UI no longer working for fleet module in Heroku

### ISSUE THREAD

**Issue by BWortman** [fusionalliance/autorenter-angular1#59]
Go here, for example, to see the error:
https://autorenter-angular1.herokuapp.com/fleet/locations

This is the most recent commit. It ran fine locally, but it does look like it could be impacting things in production/heroku: https://github.com/fusionalliance/autorenter-angular1/commit/d00f55aa2601cd3a57011b66fc50eb145a3bf06d

**Comment by JeremiahDotNet** [comment]
Hopefully fixed with this pull request #61

**Comment by JeremiahDotNet** [comment]
This will be fixed with pull request #62

**Comment by BWortman** [comment]
Good work, @JeremiahDotNet !
