### ISSUE TITLE
Login link visible even when user session active

### ISSUE THREAD

**Issue by BWortman** [fusionalliance/autorenter-angular1#68]
Sort of a corner case, but one that will be tested in "real" apps... so we should address it.

Steps to reproduce:
- Login to the app.
- Open another tab, and enter the site root URL. Note you access the landing page, but instead of the username you are presented with the Log in link. Also, the main menu is not visible:

![image](https://user-images.githubusercontent.com/6438381/31738434-b1c7490a-b418-11e7-9df0-6b9894728bf4.png)

------------

- Though the menu is missing, you can access protected parts of the app by entering in the URL directly:

![image](https://user-images.githubusercontent.com/6438381/31738227-f704950a-b417-11e7-8320-66b463bac8fb.png)

**Comment by camoore1979** [comment]
This is also occurring on a refresh.

To recreate:
1. login
2. refresh browser

**Comment by jcornfusionalliance** [comment]
it's because the render is conditional based on the in memory user object rather than the local storage credentials.  

I just submitted a PR that has a localstorage service that I'd like to use to fix this issue.  

when it's merged I'll fix this issue -- assuming I remember.

**Comment by BWortman** [comment]
Closed with PR #72
