### ISSUE TITLE
Log Out should be available as a menu item

### ISSUE THREAD

**Issue by BWortman** [fusionalliance/autorenter-angular1#70]
Please implement according to the spec: https://fusion-alliance.gitbooks.io/autorenter-spec/content/modules/main_module/main_interactions.html#logout

**Comment by jcornfusionalliance** [comment]
it seems the difference in implementation and spec is that the spec would prefer that we place logout functionality under a user dropdown.  

Right?

Because logging out already seems to work to log out user

**Comment by BWortman** [comment]
Correct.


________________________________

**Comment by jcornfusionalliance** [comment]
right on. I'll get on it

**Comment by JakeTheCorn** [comment]
@BWortman 

When the feature/user_drop_down branch gets merged to develop this issue needs to be closed. 

Thanks!

**Comment by BWortman** [comment]
Closed with PR #72
