### ISSUE TITLE
API override functionality is broken

### ISSUE THREAD

**Issue by BWortman** [fusionalliance/autorenter-angular1#71]
This functionality touted in the readme does not work:

![image](https://user-images.githubusercontent.com/6438381/33690603-3d6ceb08-dab2-11e7-847d-c140b430b117.png)

This line in `webpack.config.js` may have something to do with it:

`var targetUrl = isProd ? "https://autorenter-nodeexpress-api.herokuapp.com/api/" : "http://127.0.0.1:3000/api/";`

It would be better to use environment variables for this behavior; look into using the dotenv env module.

**Comment by jcornfusionalliance** [comment]
@BWortman 

This is more immediately graspable to me from the description than the webpack issue.  

Would you like me to have a look at this? 

We may want to create a top-level directory bin/ in which our command logic could live.  or scripts/ or commands/ ...

**Comment by BWortman** [comment]
Yes, please take a stab at it. I'm not sure what the best approach is. This is along the lines of what I'm thinking:


https://www.jvandemo.com/how-to-configure-your-angularjs-application-using-environment-variables/


________________________________

**Comment by JakeTheCorn** [comment]
@BWortman 

I've got a fix ready to push up for this but I'm going to wait until I get one branch merged in to development so I can better manage merge conflicts.

**Comment by BWortman** [comment]
Fixed with PR #76
